version: '3.7'

services:
  web:
    image: tarekaec/django_aio:1.0
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      update_config:
        order: start-first
    # entrypoint: bash ./entrypoint.sh
    env_file:
      - .env
    environment:
      DEBUG: '1'
      DJANGO_SETTINGS_MODULE: config.settings.pro
      ALLOWED_HOSTS: '127.0.0.1,127.0.0.11'
      PRODB_URL: postgres://jasmin:jasmin@172.17.0.1:5432/jasmin
      REDIS_URI: redis://redis:6379/1
      TELNET_HOST: jasmin
      SUBMIT_LOG: 1
    volumes:
      - web_public:/app/public
      - web_logs:/app/logs
    depends_on:
      - redis
  celery:
    image: tarekaec/django_aio:1.0
    entrypoint: bash ./entrypoint-celery.sh
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      DEBUG: 0
      PRODB_URL: postgres://jasmin:jasmin@172.17.0.1:5432/jasmin
      DJANGO_SETTINGS_MODULE: config.settings.pro
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_LOG_LEVEL: info
    healthcheck:
      disable: true
    depends_on:
      - redis
  redis:
    image: redis:alpine
    tty: true
    volumes:
      - redis_data:/data
    command:
      - 'redis-server'
      - '--appendonly yes'
      - '--save 60 1'
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  redis_data:
    driver: local
  web_public:
    driver: local
  web_logs:
    driver: local