# Generated by Django 3.0.5 on 2020-05-02 10:44

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('name', models.CharField(max_length=64, verbose_name='Currency Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('code', models.CharField(max_length=8, verbose_name='Currency Code')),
                ('code3', models.CharField(blank=True, max_length=8, null=True, verbose_name='Currency Code 3')),
                ('symbol', models.CharField(blank=True, max_length=8, null=True, verbose_name='Currency Symbol')),
                ('order', models.PositiveIntegerField(verbose_name='Currency Order')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ('enabled', 'order'),
            },
        ),
        migrations.CreateModel(
            name='EmailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('server', models.CharField(max_length=50, verbose_name='Server')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=50, verbose_name='Username / Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('ssl', models.BooleanField(default=True, verbose_name='SSL Support')),
                ('level', models.CharField(choices=[('admin', 'Administration'), ('security', 'Security'), ('info', 'Information')], default='info', max_length=24, verbose_name='Account Type')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Email Server',
                'verbose_name_plural': 'Email Servers',
            },
        ),
        migrations.CreateModel(
            name='Tokenizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('uidb64', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tokenizer',
                'verbose_name_plural': 'Tokenizer',
            },
        ),
    ]
