# Generated by Django 3.1.4 on 2020-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat Currency'), ('crypto', 'Crypto Currency')], default='fiat', max_length=24, verbose_name='Currency Type'),
        ),
    ]
